version: '3.8'

services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: criacerto-db
    ports:
      - "${DB_PORT}:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
    volumes:
      - mssql-data:/var/opt/mssql
    restart: always

volumes:
  mssql-data:
    driver: local
